### ISSUE TITLE
Add doxygen documentation generation

### ISSUE THREAD

**Issue by PetervDooren** [tue-robotics/emc_system#11]
We want to add documentation, especially for the emc/io object. This should contain a class reference for how to use the various functions. It should be automatically generated.

**Comment by MatthijsBurgh** [comment]
Auto- generation enabled by https://github.com/tue-robotics/tue-env-targets/pull/353

**Comment by PetervDooren** [comment]
Docs are auto generated with https://github.com/tue-robotics/tue-env-targets/pull/353 and #12
