### ISSUE TITLE
emc-system destructor does not work

### ISSUE THREAD

**Issue by PetervDooren** [tue-robotics/emc_system#6]
To replicate: create an executable with an emc::io and return 0. 
You will see the following error message:
```
terminate called after throwing an instance of 'boost::wrapexcept<boost::lock_error>'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Aborted (core dumped)
```

**Comment by MatthijsBurgh** [comment]
Please define what constructor should be used.

**Comment by KdVos** [comment]
Minimal example of the issue 

#include <emc/io.h>

int main(int argc, char *argv[])
{
    // Initialize the robot
    emc::IO io;

    while(io.ok())
    {

        return 0;
    }
}
